CFLAGS=-Wall -Werror -Wextra

print_module:
	gcc $(CFLAGS) print_module.c main_module_entry_point.c -o ../build/Quest_1

documentation_module:
	gcc $(CFLAGS) print_module.c main_module_entry_point.c documentation_module.c -o ../build/Quest_2

bst_create_test:
	gcc $(CFLAGS) bst.c bst_create_test.c -o ../build/Quest_3

bst_insert_test:
	gcc $(CFLAGS) bst.c bst_insert_test.c -o ../build/Quest_4

bst_traverse_test:
	gcc $(CFLAGS) bst.c bst_traverse_test.c -o ../build/Quest_5